name: Sign Artifact with SBOM

on:
  workflow_call:
    inputs:
      subject-name:
            required: true
            type: string
      sbom-path:
            required: true
            type: string

jobs:
  sign-artifact:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read

    steps:
    - name: Attest Build Provenance
      uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd # v2.3.0
      with:
        subject-name: ${{ inputs.subject-name }}

    - name: Attest SBOM
      uses: actions/attest-sbom@115c3be05ff3974bcbd596578934b3f9ce39bf68 # v2.2.0
      with:
        subject-path: ${{ inputs.subject-name }}
        sbom-path: ${{ inputs.sbom-path }}