name: Sign Artifact with SBOM

on:
  workflow_call:
    inputs:
      subject-name:
            required: true
            type: string
      sbom-path:
            required: true
            type: string

jobs:
  sign-artifact:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read

    steps:
    - name: Attest Build Provenance
      uses: actions/attest-build-provenance@e8998f949152b193b063cb0ec769d69d929409be # v2.4.0
      with:
        subject-name: ${{ inputs.subject-name }}

    - name: Attest SBOM
      uses: actions/attest-sbom@bd218ad0dbcb3e146bd073d1d9c6d78e08aa8a0b # v2.4.0
      with:
        subject-path: ${{ inputs.subject-name }}
        sbom-path: ${{ inputs.sbom-path }}